# Generated by Django 4.2.5 on 2023-10-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_contacto_avisos_contacto_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('apellido', models.CharField(max_length=30)),
                ('dpi', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='catedratico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.docente', to_field='nombre'),
            preserve_default=False,
        ),
    ]
