# Generated by Django 4.2.5 on 2023-10-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_docente_curso_catedratico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='dpi',
            field=models.CharField(max_length=13),
        ),
    ]
