# Generated by Django 4.2.5 on 2023-11-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_docente_dpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('apellido', models.CharField(max_length=30)),
                ('dpi', models.CharField(max_length=13)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='catedratico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.perfil', to_field='nombre'),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
