# Generated by Django 4.2.5 on 2023-11-01 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_perfil_alter_curso_catedratico_delete_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='catedratico',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
