# Generated by Django 4.2.5 on 2023-11-01 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0008_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes_inscritos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
