# Generated by Django 4.2.5 on 2023-11-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_curso_estudiantes_inscritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cantidad_estudiantes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
