# Generated by Django 4.2.5 on 2023-11-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_docente_curso_docentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='docentes',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
