# Generated by Django 4.2.5 on 2023-11-04 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_curso_docente_curso_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
